import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "./globals.css";
import StarCanvas from "./_components/star";
import { Toaster } from "sonner"

const kanit = Kanit({
  subsets: ["latin"],
  variable: "--font-serif",
  weight: [
    "100",
    "200",
    "300",
    "400",
    "500",
    "600",
    "700",
    "800",
    "900",
  ]
})



export const metadata: Metadata = {
  title: "Kryfal ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${kanit.className} bg-black text-white antialiased`}
      >
        <StarCanvas />
        {children}
        <Toaster richColors position="top-right" /> {/* Notificação */}
      </body>
    </html>
  );
}
