import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "../../app/globals.css";
import StarCanvas from "../_components/star";
import { Toaster } from "sonner";
import { NextIntlClientProvider } from "next-intl";

// Font
const kanit = Kanit({
  subsets: ["latin"],
  variable: "--font-serif",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Kryfal",
  description: "Generated by create next app",
};

const SUPPORTED_LOCALES = ["en", "pt"];

interface RootLayoutProps {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}

export default async function RootLayout({ children, params }: RootLayoutProps) {
  const rawLocale = (await params).locale;
  const locale = SUPPORTED_LOCALES.includes(rawLocale) ? rawLocale : "en";

  // Tipo seguro para qualquer JSON de mensagens i18n
  let messages: Record<string, unknown> = {};
  try {
    messages = (await import(`../../messages/${locale}.json`)).default;
  } catch {
    if (process.env.NODE_ENV === "development") {
      console.warn(`Locale "${locale}" não encontrado, usando "en".`);
    }
    messages = (await import(`../../messages/en.json`)).default;
  }

  return (
    <html lang={locale}>
      <body className={`${kanit.className} bg-black text-white antialiased`}>
        <StarCanvas />
        <NextIntlClientProvider locale={locale} messages={messages}>
          {children}
        </NextIntlClientProvider>
        <Toaster richColors position="top-right" />
      </body>
    </html>
  );
}
